In [52]:
import numpy as np
from lib import weat

In [51]:
!pip3 install scipy

     |████████████████████████████████| 30.9 MB 17.5 MB/s eta 0:00:01


In [46]:
emb1 = np.matrix('0.01 0.02 0.03; 0.8 0.9 0.6')

In [47]:
emb2 = np.matrix('0.5, 0.02 0.03; 0.8 0.9 0.6')

In [20]:
emb1

matrix([[0.01, 0.02, 0.03],
        [0.8 , 0.9 , 0.6 ]])

In [25]:
emb2

matrix([[0.5 , 0.02, 0.03],
        [0.8 , 0.9 , 0.9 ]])

In [28]:
emb1.T

matrix([[0.01, 0.8 ],
        [0.02, 0.9 ],
        [0.03, 0.6 ]])

In [26]:
emb2.T

matrix([[0.5 , 0.8 ],
        [0.02, 0.9 ],
        [0.03, 0.9 ]])

In [36]:
def pip(mat): 
    return np.matmul(mat, mat.T)

In [37]:
loss = pip(emb1) - pip(emb2)

In [39]:
pip(emb1)

matrix([[1.40e-03, 4.40e-02],
        [4.40e-02, 1.81e+00]])

In [40]:
pip(emb2)

matrix([[0.2513, 0.445 ],
        [0.445 , 2.26  ]])

In [41]:
loss

matrix([[-0.2499, -0.401 ],
        [-0.401 , -0.45  ]])

## word differences in word embeddings
The purpose is to find the relative similarity between a word in two sets of word embeddings. The two sets of word embeddings will need to have the same vocabulary. We take the cosine similarity between a word i and all word j in a word embeddings, and take its mean. We do the same with the second set of word embeddings, and find the absolute difference. 

If a word has a high effect size, then its perceived differently between the two word embeddings. 
Cons: high computation to do this for each word. 
1. mean(sum(M1_i, M1_j)) for all j rows in M1
2. mean(sum(M2_i, M2_j)) for all j rows in M2
3. | mean(sum(M1_i, M1_j)) - mean(sum(M2_i, M2_j)) | / stdev(M1_i, M2_i)


In [44]:
def cosine_similarity(mat):
    num = mat.T @ mat
    den = np.linalg.norm(mat)
    
    return num / den / den.T

In [48]:
cosine_similarity(emb1)

matrix([[0.35337308, 0.39759302, 0.26515402],
        [0.39759302, 0.44738876, 0.29844319],
        [0.26515402, 0.29844319, 0.19923816]])

In [54]:
weat = weat.Weat()

In [65]:
emb1

matrix([[0.01, 0.02, 0.03],
        [0.8 , 0.9 , 0.6 ]])

In [75]:
emb1_array = np.squeeze(np.asarray(emb1[0,:]))
emb1_array2 = np.squeeze(np.asarray(emb1[1,:]))

emb2_array = np.squeeze(np.asarray(emb2[0,:]))
emb2_array2 = np.squeeze(np.asarray(emb2[1,:]))

In [77]:
diff_cos = np.abs(weat.mean_cos_similarity(emb1_array, emb1_array2)- \
weat.mean_cos_similarity(emb2_array, emb2_array2))

In [ ]:
denom = np.sqrt(((dof-1)*np.std(cos_similarities, ddof=1) **2 ) / (dof-1))

In [78]:
diff_cos/

0.16880544852988388